site_name: Awesome Kubernetes
site_url: https://awesome-kubernetes.readthedocs.io
site_description: A curated list of awesome IT projects and resources. Inspired by the awesome list.
site_author: inafev

repo_url: https://github.com/inafev/awesome-kubernetes

theme: readthedocs
extra_css:
- extra.css
extra_javascript:
- extra.js
site_favicon: images/favicon.ico
markdown_extensions:
- smarty
- sane_lists
- fenced_code
- meta
- admonition
- toc:
    permalink: True
pages:
- Home: index.md
- Introduction:
  - Openshift VS Kubernetes: introduction.md
  - From Java EE To Cloud Native: javaee-to-cloud-native.md
  - Microservices FAQ & Kubernetes Native: faq.md
  - Serverless with OpenFaaS & Knative: serverless.md
- DevOps: devops.md
- CI/CD: cicd.md
- TestOps: testops.md
- Docker: docker.md
- Kubernetes: 
  - Kubernetes: kubernetes.md
  - Kubernetes Matrix Table: matrix-table.md
  - Kubernetes alternatives: kubernetes-alternatives.md
- Openshift: 
  - Openshift docs: openshift.md
  - List of Openshift Compliant Docker images. Demos : openshift-compliant-images.md
  - Monitoring and Performance : monitoring.md
  - Java Performance Optimization: java-and-java-performance-optimization.md
  - Java Parameters Matrix Table: jvm-parameters-matrix-table.md
- Jenkins & Cloudbees: 
  - Jenkins docs: jenkins.md
  - Performance testing with Jenkins and JMeter or Gatling : performance-testing-with-jenkins-and-jmeter.md
  - Jenkins and Openshift. Demos : jenkins-and-openshift.md
  - Groovy: groovy.md
  - Jenkins Scripts: scripts/README.md
  - CI/CD alternatives: cicd-alternatives.md
- Toolchain:
  - Maven: maven.md
  - Gradle: gradle.md
  - Podman & Buildah: podman.md
  - SonarQube: sonarqube.md
  - Nexus: nexus.md
  - JFrog Artifactory: artifactory.md
  - Apache: apache.md
  - HAProxy: haproxy.md
  - Payara: payara.md
  - Zephyr Jira plugin: zephyr.md
  - Selenium: selenium.md
  - Appium: appium.md
  - SSH: ssh.md
  - Work From Home: workfromhome.md
- Configuration Management:
  - Terraform & Packer: terraform.md
  - Ansible: ansible.md
  - Liquibase: liquibase.md
- Databases on Kubernetes: databases.md
- Caching Solutions: caching.md
- Streaming & Messaging. Cloud Based Integration: message-queue.md
- Service Mesh: 
  - Service Mesh: servicemesh.md
  - Istio Service Mesh: istio.md
  - Consul Service Mesh: consul.md
- Security Policy as Code: securityascode.md
- Cloud Native Storage: storage.md
- Dev Environment:
  - Git & Git Flow: git.md
  - Visual Studio: visual-studio.md
  - GitKraken: gitkraken.md
  - WSL - Linux Dev Environment on Windows: linux-dev-env.md
  - Scaffolding Tools: scaffolding.md
- Frameworks:
  - Angular: angular.md
  - Java - Spring Framework: SpringFramework.md
  - Java - SpringBoot: SpringBoot.md
  - Java - Spring Cloud: SpringCloud.md
  - Java - Quarkus: quarkus.md
  - Python: python.md
  - Xamarin: xamarin.md
- APIs:
  - APIs and RESTful Architecture: apis-and-restful-architecture.md
  - API Marketplaces. Developer Portals and API Management/API Gateway: developerportals.md
  - 3scale API Management: 3scale.md
  - Test Automation with Postman: postman.md
  - Swagger code generator for REST APIs: swagger-code-generator-for-rest-apis.md
- TestOps: testops.md
- Demos: demos.md
- Public Cloud: 
  - Public Cloud Solutions: public-cloud-solutions.md
  - Edge Computing: edge-computing.md
  - Cloud Architecture Diagram Tools: cloud-arch-diagrams.md
  - AWS: aws.md
  - Google Cloud Platform: GoogleCloudPlatform.md
  - Microsoft Azure: azure.md
  - Digital Ocean: digitalocean.md
  - Cloudflare: cloudflare.md
- E-Learning: elearning.md
- Customer Success Stories: customer.md
- Subreddits: newsfeeds.md
- Other Awesome Lists: other-awesome-lists.md
- About: about.md

copyright: 2020 <a href="https://twitter.com/RedHatSpain">Red Hat Spain (Unofficial linkedin group)</a>, <a href="https://awesome-kubernetes.readthedocs.io/about/">about</a>.
google_analytics: ['UA-126665400-1', 'awesome kubernetes']
