site_name: Awesome Kubernetes
site_url: https://redhatspain.com
site_description: A curated list of awesome IT projects and resources. Inspired by the awesome list.
site_author: info@redhatspain.com
docs_dir: docs/
repo_name: 'GitHub'
repo_url: https://github.com/redhatspain/awesome-kubernetes
theme: 
  name: material 
  prev_next_buttons_location: both
  #navigation_depth: 4
  #titles_only: False
  #sticky_navigation: True
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
extra_css:
  - static/extra.css
extra_javascript:
  - javascript/extra.js
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details 
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: True
nav:
  - Home: index.md
  - Introduction:
    - From Java EE To Cloud Native. Microservice Architecture. Openshift VS Kubernetes: introduction.md
    - Microservices FAQ & Kubernetes Native: faq.md
  - SRE: sre.md
  - Serverless: serverless.md
  - DevOps:
    - DevOps: devops.md
    - Cheat Sheets: cheatsheets.md
    - GitOps: gitops.md
    - MLOps: mlops.md
    - Chaos Engineering: chaos-engineering.md
  - Demos and Boilerplates:
    - Demos, Boilerplates & Screencasts: demos.md
  - DevSecOps:
    - DevSecOps. Container Security: devsecops.md
    - Security Policy as Code: securityascode.md
  - NoOps: 
    - NoOps: noops.md
    - Serverless Architectures & Frameworks. OpenFaaS, Knative & Kubeless: serverless.md
  - FinOps: finops.md
  - TestOps:
    - TestOps and Continuous Testing: testops.md
    - QA: qa.md
  - Docker: docker.md
  - Kubernetes: 
    - Kubernetes: kubernetes.md
    - Kubernetes Plugins, Tools, Extensions and Projects: kubernetes-tools.md
    - kubectl commands: kubectl-commands.md
    - Kubernetes Networking: kubernetes-networking.md
    - Kubernetes Monitoring and Logging: kubernetes-monitoring.md
    - Kubernetes security: kubernetes-security.md
    - Kubernetes Storage: kubernetes-storage.md
    - Kubernetes Backup and Migrations: kubernetes-backup-migrations.md
    - Kubernetes autoscaling: kubernetes-autoscaling.md
    - Kubernetes Operators and Controllers: kubernetes-operators-controllers.md
    - Kubernetes Based Development: kubernetes-based-devel.md
    - Kubernetes on premise: kubernetes-on-premise.md
    - Managed kubernetes in public clouds: managed-kubernetes-in-public-cloud.md
    - Kubernetes Releases: kubernetes-releases.md
    - Kubernetes Matrix Table: matrix-table.md
    - Kubernetes alternatives: kubernetes-alternatives.md
  - Rancher:     
    - Rancher - Enterprise management for Kubernetes: rancher.md
  - OpenShift: 
    - OpenShift docs: openshift.md
    - OCP 3: ocp3.md
    - OCP 4: ocp4.md
  - Software Delivery: 
    - CI/CD - Continuous Integration & Continuous Delivery: cicd.md
    - Git & Git Patterns. Trunk Devel, Git Flow & Feature Flags. Merge BOTs: git.md 
    - Jenkins & Cloudbees: jenkins.md
    - OpenShift Pipelines with Jenkins, Tekton and more...: openshift-pipelines.md
    - Performance testing with Jenkins and JMeter or Gatling : performance-testing-with-jenkins-and-jmeter.md
    - Jenkins Alternatives for Continuous Integration: jenkins-alternatives.md
    - Toolchain:
      - Container Runtimes/Managers & Base Images. Podman, Buildah & Skopeo: container-managers.md
      - Maven, Gradle & SDKMAN: maven-gradle.md
      - SonarQube: sonarqube.md
      - Docker Registries. Quay, Nexus, JFrog Artifactory, Harbor and more: registries.md
      - Selenium, Cucumber, Appium & Zephyr Jira plugin: selenium-appium-zephyr.md
      - Linux & SSH: linux.md
      - MkDocs & GitHub Pages: mkdocs.md
    - Web Servers, Reverse Proxies, Java Runtimes & Caching Solutions: 
      - Web Servers & Reverse Proxies - Apache, Nginx, HAProxy, Traefik and more: web-servers.md
      - Java EE/Jakarta EE and MicroProfile Runtimes - Payara, JBoss EAP, WebSphere Liberty, WildFly and more: java_app_servers.md
      - Embedded Servlet Containers in SpringBoot: embedded-servlet-containers.md
      - Caching Solutions: caching.md
  - Monitoring:
    - Monitoring and Performance: monitoring.md
    - Prometheus: prometheus.md
    - Grafana: grafana.md
  - Config Management:
    - Ansible: ansible.md
    - Argo CD - Declarative GitOps for Kubernetes: argocd.md
    - Chef: chef.md
    - CI/CD Kubernetes Plugins: cicd-kubernetes-plugins.md
    - Client Libraries for Kubernetes - Go client, Python, Fabric8, JKube & Java Operator SDK: kubernetes-client-libraries.md
    - Helm Kubernetes Tool: helm.md
    - Database Version Control. Liquibase, Flyway and PlanetScale: liquibase.md
    - Template-Free Kubernetes Configuration Customization with Kustomize: kustomize.md
    - Templating YAML with YAML Processors. Static Checking of Kubernetes YAML Files: yaml.md
  - Infra Mgmt Tools:
    - IaC Infrastructure as Code: iac.md
    - Pulumi: pulumi.md
    - Terraform & Packer. K8s boilerplates: terraform.md
    - Crossplane: crossplane.md
  - Databases: 
    - Relational Databases and Database DevOps: databases.md
    - NoSQL Databases: nosql.md
  - Data Pipeline: message-queue.md
  - Service Mesh: 
    - Service Mesh: servicemesh.md
    - Istio: istio.md
  - APIs:
    - APIs with SOAP, REST and gRPC: api.md
    - Swagger code generator for REST APIs: swagger-code-generator-for-rest-apis.md
    - API Test Automation with Postman: postman.md
    - API Marketplaces. API Management with API Gateways & Developer Portals : developerportals.md
  - Devel:
    - Angular: angular.md
    - Document Object Model (DOM): dom.md
    - Go: golang.md
    - JavaScript - node.js & npm: javascript.md
    - Python - Django & Flask: python.md
    - Microsoft Xamarin: xamarin.md
    - Microsoft .NET: dotnet.md
    - Websites for web developers: devel-sites.md
    - Java:
      - Java & Open Source Microservices Frameworks. SpringBoot, MicroProfile, Quarkus and more: java_frameworks.md
      - Java Memory Management & Java Performance Optimization: java-and-java-performance-optimization.md
      - Java Parameters Matrix Table: jvm-parameters-matrix-table.md
    - Dev Environment:
      - Visual Studio Code: visual-studio.md
      - WSL - Linux Dev Environment on Windows: linux-dev-env.md
      - Scaffolding Tools: scaffolding.md
      - Chrome & Firefox DevTools. HTTP Protocols & WebSockets: ChromeDevTools.md
      - Low Code and No Code: lowcode-nocode.md
      - Web 3: web3.md
      - Digital Money: digital-money.md
  - Cloud: 
    - Public Cloud Solutions: public-cloud-solutions.md
    - Edge Computing: edge-computing.md
    - Cloud Architecture Diagram Tools: cloud-arch-diagrams.md
    - AWS: aws.md
    - Google Cloud Platform: GoogleCloudPlatform.md
    - Microsoft Azure: azure.md
    - IBM & IBM Cloud: ibm_cloud.md
    - Oracle Cloud: oraclecloud.md
    - Digital Ocean: digitalocean.md
    - Cloudflare: cloudflare.md
  - Big Data: bigdata.md
  - Project Management:
    - Project Management Methodology: project-management-methodology.md
    - Project Management Tools: project-management-tools.md
    - Appointment Scheduling: appointment-scheduling.md
    - Work From Home: workfromhome.md
  - More References:
    - E-Learning: elearning.md
    - Subreddits: newsfeeds.md
    - Other Awesome Lists: other-awesome-lists.md
  - Recruitment:
    - Recruitment: recruitment.md
    - Freelancing: freelancing.md
    - Remote Tech Jobs: remote-tech-jobs.md
  - Clients: customer.md
  - About: about.md
copyright: 2021 <a href="https://twitter.com/RedHatSpain">Red Hat Spain</a>, <a href="https://redhatspain.com/about/">about</a>.
google_analytics: ['UA-168051035-1', 'redhatspain.com']
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/redhatspain
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/1937212/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/redhatspain
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCCGQ2G2rGAkHzVFhhed-xVw/playlists
    - icon: fontawesome/brands/speaker-deck
      link: https://speakerdeck.com/redhatspain/stars
    - icon: fontawesome/brands/slideshare
      link: https://es.slideshare.net/RedHatSpain/favorites
    - icon: fontawesome/brands/slack
      link: https://redhatspain.slack.com/
