site_name: Awesome Kubernetes
site_url: https://awesome-kubernetes.readthedocs.io
site_description: A curated list of awesome IT projects and resources. Inspired by the awesome list.
site_author: inafev

repo_url: https://github.com/inafev/awesome-kubernetes

theme: readthedocs
extra_css:
- extra.css
extra_javascript:
- extra.js
site_favicon: images/favicon.ico
markdown_extensions:
- smarty
- sane_lists
- fenced_code
- meta
- admonition
- toc:
    permalink: True
pages:
- Home: index.md
- Introduction:
  - Openshift VS Kubernetes: introduction.md
  - From Java EE To Cloud Native: javaee-to-cloud-native.md
  - Microservices FAQ & Kubernetes Native: faq.md
- DevOps: devops.md
- TestOps and Continuous Testing: testops.md
- CI/CD: 
  - CI/CD - Continuous Integration & Continuous Delivery: cicd.md
  - Git & Git Patterns. Git Flow & Trunk. Merge BOTs: git.md
- Docker: docker.md
- Kubernetes: 
  - Kubernetes: kubernetes.md
  - Kubernetes Matrix Table: matrix-table.md
  - Kubernetes alternatives: kubernetes-alternatives.md
- Openshift: 
  - Openshift docs: openshift.md
  - Monitoring and Performance. Prometheus, Grafana, APMs and more: monitoring.md
  - Java Performance Optimization: java-and-java-performance-optimization.md
  - Java Parameters Matrix Table: jvm-parameters-matrix-table.md
- Jenkins & Cloudbees: 
  - Jenkins docs: jenkins.md
  - Performance testing with Jenkins and JMeter or Gatling : performance-testing-with-jenkins-and-jmeter.md
  - OpenShift Pipelines with Jenkins, Tekton and more...: openshift-pipelines.md
  - Groovy: groovy.md
  - Jenkins Scripts: scripts/README.md
  - Jenkins Alternatives for Continuous Integration: jenkins-alternatives.md
- Toolchain:
  - Container Runtimes/Managers & Base Images. Podman, Buildah & Skopeo: container-managers.md
  - Maven: maven.md
  - Gradle: gradle.md
  - SonarQube: sonarqube.md
  - Nexus: nexus.md
  - JFrog Artifactory: artifactory.md
  - Apache: apache.md
  - HAProxy: haproxy.md
  - Payara: payara.md
  - Zephyr Jira plugin: zephyr.md
  - Selenium: selenium.md
  - Appium: appium.md
  - SSH: ssh.md
  - Work From Home: workfromhome.md
  - Appointment Scheduling: appointment-scheduling.md
- Configuration Management:
  - Ansible: ansible.md
  - Liquibase: liquibase.md
  - Terraform & Packer: terraform.md
- Databases on Kubernetes: 
  - Relational Databases: databases.md
  - NoSQL Databases: nosql.md
- Caching Solutions: caching.md
- Streaming & Messaging. Cloud Based Integration: message-queue.md
- Service Mesh: 
  - Service Mesh: servicemesh.md
  - Consul: consul.md
  - Envoy & xDS protocol: envoyproxy.md
  - Istio: istio.md
  - Linkerd: linkerd.md
  - Maesh: maesh.md
  - Traffic Director: trafficdirector.md
- Security and DevSecOps:
  - DevSecOps. Container Security: devsecops.md
  - Security Policy as Code: securityascode.md
  - Security Patterns for Microservice Architectures: security-patterns-microservice.md
- Cloud Native Storage: storage.md
- APIs:
  - APIs with SOAP, REST and gRPC: api.md
  - Swagger code generator for REST APIs: swagger-code-generator-for-rest-apis.md
  - Test Automation with Postman: postman.md
  - API Marketplaces and Developer Portals: developerportals.md
  - 3scale API Management: 3scale.md
- Development & Frameworks:
  - Angular: angular.md
  - Document Object Model (DOM): dom.md
  - Java - Spring Framework: SpringFramework.md
  - Java - SpringBoot: SpringBoot.md
  - Java - Spring Cloud: SpringCloud.md
  - Java - Quarkus: quarkus.md
  - JavaScript - node.js & npm: javascript.md
  - Python - Django & Flask: python.md
  - Xamarin: xamarin.md
- Serverless Architectures & Frameworks. OpenFaaS, Knative & Kubeless: serverless.md
- Dev Environment:
  - Visual Studio Code: visual-studio.md
  - WSL - Linux Dev Environment on Windows: linux-dev-env.md
  - Scaffolding Tools: scaffolding.md
  - ChromeDevTools: ChromeDevTools.md
- Demos: demos.md
- Public Cloud: 
  - Public Cloud Solutions: public-cloud-solutions.md
  - Edge Computing: edge-computing.md
  - Cloud Architecture Diagram Tools: cloud-arch-diagrams.md
  - AWS: aws.md
  - Google Cloud Platform: GoogleCloudPlatform.md
  - Microsoft Azure: azure.md
  - Oracle Cloud: oraclecloud.md
  - Digital Ocean: digitalocean.md
  - Cloudflare: cloudflare.md
- E-Learning: elearning.md
- Customer Success Stories: customer.md
- Subreddits: newsfeeds.md
- Other Awesome Lists: other-awesome-lists.md
- About: about.md

copyright: 2020 <a href="https://twitter.com/RedHatSpain">Red Hat Spain (Unofficial linkedin group)</a>, <a href="https://awesome-kubernetes.readthedocs.io/about/">about</a>.
google_analytics: ['UA-126665400-1', 'awesome kubernetes']
