site_name: Awesome Kubernetes
site_url: https://awesome-kubernetes.readthedocs.io
site_description: A curated list of awesome IT projects and resources. Inspired by the awesome list.
site_author: inafevwork

repo_url: https://github.com/inafevwork/awesome-kubernetes

theme: readthedocs
extra_css:
- extra.css
extra_javascript:
- extra.js
site_favicon: images/favicon.ico
markdown_extensions:
    - smarty
    - sane_lists
    - toc:
        permalink: True
    - admonition
pages:
- Home: index.md
- CI/CD : cicd.md
- Jenkins : jenkins.md
- Performance Testing with Jenkins and JMeter : performance-testing-with-jenkins-and-jmeter.md
- Jenkins and Openshift : jenkins-and-openshift.md
- Docker: docker.md
- Kubernetes : kubernetes.md
- Openshift Kubernetes : openshift.md
- Java and Java Performance Optimization: java-and-java-performance-optimization.md
- Debugging java applications on openshift and kubernetes: debugging-java-applications-on-openshift-and-kubernetes.md
- Troubleshooting openshift network performance: troubleshooting-openshift-network-performance.md
- SonarQube: sonarqube.md 
- Nexus: nexus.md
- Maven: maven.md 
- Git: git.md
- Visual Studio: visual-studio.md
- Terraform: terraform.md
- Ansible: ansible.md
- Groovy: groovy.md
- APIs and RESTful Architecture: apis-and-restful-architecture.md
- Swagger code generator for REST APIs: swagger-code-generator-for-rest-apis.md
- Public Cloud Solutions : public-cloud-solutions.md
- About: about.md

copyright: Copyright &copy; 2018 <a href="https://twitter.com/RedHatSpain">Red Hat Spain (Community Linkedin Group)</a>, <a href="http://awesome-kubernetes.readthedocs.io/en/latest/about/">about</a>.
google_analytics: ['', 'awesome kubernetes']
